name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup SSH key
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      - name: Deploy and Run Bonga Admin Application
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
            set -e  # Stop on error
            cd /var/www/bonga-admin

            echo "Pulling latest changes..."
            git pull origin main

            echo "Installing dependencies..."
            yarn

            echo "Building react app..."
            yarn build
            echo "Bonga deployed successfully!"
          EOF
